labels: ["Triage needed"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please read through our [contributor guidelines](https://stackio.shadowarcanist.com/core/contributor-guidelines), and check for both existing [Discussions](https://github.com/ShadowArcanist/Stackio/discussions) and [Issues](https://github.com/ShadowArcanist/Stackio/issues) prior to opening a new Discussion.

  - type: textarea
    attributes:
      label: Explain your idea or suggestion
      description: |
        Provide context or information for the discussion.

  - type: checkboxes
    attributes:
      label: "I acknowledge that:"
      options:
        - label: I have reviewed discussion and confirm that my idea/suggestion is NOT among them.
          required: true
        - label: I have searched the [Stackio repository](https://github.com/ShadowArcanist/Stackio) (both open and closed Discussions and Issues) and confirm this is not a duplicate of an existing issue or discussion.
          required: true
