labels: ["Triage needed"]
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]
        > Please read through our [contributor guidelines](https://stackio.shadowarcanist.com/core/contributor-guidelines), and check for both existing [Discussions](https://github.com/ShadowArcanist/Stackio/discussions) and [Issues](https://github.com/ShadowArcanist/Stackio/issues) prior to opening a new Discussion.
  
  - type: input
    attributes:
      label: Application Name
      description: |
        Enter the name of the application.
      placeholder: |
        Netbird
    validations:
      required: true
      
  - type: input
    attributes:
      label: Stackio Link
      description: |
        Provide the URL of the application guide on Stackio.
      placeholder: |
        https://stackio.shadowarcanist.com/application/vpn/netbird
    validations:
      required: true

  - type: textarea
    attributes:
      label: Error message and logs
      description: |
        Provide a detailed description of the error or exception you encountered, along with any relevant log output.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: |
        Please provide a step-by-step guide to reproduce the issue. Be as detailed as possible, otherwise we may not be able to assist you.
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps you’ve taken to fix the Issue
      description: |
        Please explain step by step what you’ve tried to fix the issue. If you haven’t tried to solve it yourself, it will be harder for us to help you.
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true
      
  - type: input
    attributes:
      label: Coolify Version
      description: |
        Please provide the Coolify version you are using. This can be found in the top left corner of your Coolify dashboard.
      placeholder: |
        v4.0.0-beta.444
    validations:
      required: true

  - type: input
    attributes:
      label: Operating System and Version (self-hosted)
      description: |
        Run `cat /etc/os-release` or `lsb_release -a` in your terminal and provide the operating system and version.
      placeholder: |
        Ubuntu 22.04

  - type: textarea
    attributes:
      label: Additional Information
      description: |
        Any other relevant details about the issue.
      
  - type: checkboxes
    attributes:
      label: "I acknowledge that:"
      options:
        - label: I have reviewed discussion and confirm that my support request is NOT among them.
          required: true
        - label: I have searched the Stackio repository (both open and closed Discussions and Issues) and confirm this is not a duplicate of an existing issue or discussion.
          required: true